version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: root:root
    networks:
      - proxy
    environment:
      - FB_BASEURL=/
    volumes:
      - ./data:/data
      - ./config:/config
    ports:
      - 8089:8080  

networks:
  proxy:
    external: true
