---
services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: root:root
    environment:
      - FB_BASEURL=/
    volumes:
      - ./data:/data
      - ./config:/config
    ports:
      - 8089:8080  
    restart: unless-stopped