version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: root:root
    networks:
      - proxy
    environment:
      - FB_BASEURL=/
    volumes:
      - /home/serveradmin:/data
      - /home/serveradmin/filebrowser/config:/config
    ports:
      - 8089:8080  
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.filebrowser.entrypoints=http"
       - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.local.example.com`)"
       - "traefik.http.middlewares.filebrowser-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.filebrowser.middlewares=filebrowser-https-redirect"
       - "traefik.http.routers.filebrowser-secure.entrypoints=https"
       - "traefik.http.routers.filebrowser-secure.rule=Host(`filebrowser.local.example.com`)"
       - "traefik.http.routers.filebrowser-secure.tls=true"
       - "traefik.http.routers.filebrowser-secure.service=filebrowser"
       - "traefik.http.services.filebrowser.loadbalancer.server.port=8080"
       - "traefik.docker.network=proxy"
       - 'traefik.http.routers.filebrowser-secure.middlewares=authelia@docker'

networks:
  proxy:
    external: true
