---
services:
  kali:
    image: linuxserver/kali-linux:latest
    container_name: kali-linux
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Malta
      - SUBFOLDER=/ 
      - "TITLE=Kali Linux" 
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 3000:3000
      - 3001:3001  
    shm_size: "1gb" 
    restart: unless-stopped