---
  services:
    web:
      image: 'gitlab/gitlab-ce:latest'
      container_name: gitlab
      restart: unless-stopped
      networks:
        - gitlab
      hostname: 'gitlab.example.com'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://gitlab.example.com'
      ports:
        - '80:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - './config:/etc/gitlab'
        - './logs:/var/log/gitlab'
        - './data:/var/opt/gitlab'
      shm_size: '256m'
  
    registry:
      image: registry:latest
      container_name: registry
      ports:
        - 5000:5000
      volumes:
        - ./registry:/var/lib/registry
      networks:
        - gitlab
      restart: unless-stopped
  
  networks:
    gitlab:
      external: true