---
services:
  diskover:
    image: lscr.io/linuxserver/diskover
    container_name: diskover
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    volumes:
      - ./config:/config
      - data:/data
    ports:
      - 80:80
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
    # depends_on:
    #   - elasticsearch-helper
    restart: unless-stopped

  elasticsearch-helper:
    image: alpine
    networks:
      - backend
    command: sh -c "sysctl -w vm.max_map_count=262144"
    privileged: true

networks:
  backend:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=127.0.0.1,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/storage/"   