---
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana #chown 472.472 -R /home/serveradmin/grafana
    restart: unless-stopped

volumes:
  grafana-data:
    driver: local