---
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Malta
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - config:/config
      - movies:/movies
      - series:/series
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - backend

volumes:
  config:
    driver: local
  movies:
    driver: local
  series:
    driver: local
    
networks:
  backend:
    external: true
