---
services:
  redis:
    image: docker.io/library/redis:alpine
    container_name: redis-xng
    command: redis-server --save 30 1 --loglevel warning
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - redis-data:/data
    networks:
      - backend

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - SEARXNG_BASE_URL=https://searxng.example.com
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - "8088:8080"

volumes:
  redis-data: