---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - config:/config
      - movies:/movies
      - series:/series
    env_file:
      - .env           
    restart: unless-stopped

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=127.0.0.1,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/nfs/docker/plex/config"
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=127.0.0.1,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/nfs/plex/movies"
  series:
    driver_opts:
      type: "nfs"
      o: "addr=127.0.0.1,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/nfs/plex/series"