---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC 
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - JELLYFIN_PublishedServerUrl=192.168.10.10
    ports:
      - 8096:8096      
    volumes:
      - ./config:/config
      - /mnt/series:/data/tvshows
      - /mnt/movies:/data/movies
      - /mnt/music:/data/music
    restart: unless-stopped       