---
services:
  airsonic-advanced:
    image: airsonic/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 4040:4040    
    volumes:
      - ./data:/airsonic/data
      - ./music:/airsonic/music
      - ./playlists:/airsonic/playlists
      - ./podcasts:/airsonic/podcasts
    restart: unless-stopped   