version: "3"

services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    networks:
      - proxy    
    volumes:
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=http"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.local.example.com`)"
      - "traefik.http.middlewares.guacamole-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.guacamole.middlewares=guacamole-https-redirect"
      - "traefik.http.routers.guacamole-secure.entrypoints=https"
      - "traefik.http.routers.guacamole-secure.rule=Host(`guacamole.local.example.com`)"
      - "traefik.http.routers.guacamole-secure.tls=true"
      - "traefik.http.routers.guacamole-secure.service=guacamole"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - 'traefik.http.routers.guacamole-secure.middlewares=authelia@docker'
    restart: unless-stopped

networks:
  proxy:
    external: true