---
networks:
  graynet:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  log_data:
    driver: local
  graylog_data:
    driver: local

services:
  mongo:
    image: mongo:6.0.5-jammy
    container_name: mongodb
    volumes:
      - "mongo_data:/data/db"
    networks:
      - backend
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    volumes:
      - "log_data:/usr/share/opensearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200/tcp
    networks:
      - backend
    restart: unless-stopped

  graylog:
    image: graylog/graylog:5.0
    container_name: graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: ${PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${PASSWORD_SHA2}
      GRAYLOG_HTTP_BIND_ADDRESS: ${BIND_ADDRESS}
      GRAYLOG_HTTP_EXTERNAL_URI: ${EXTERNAL_URI}
      GRAYLOG_ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
      GRAYLOG_MONGODB_URI: ${MONGODB_URI}
      GRAYLOG_TIMEZONE: ${TIMEZONE}
      TZ: "Europe/Malta"
      GRAYLOG_TRANSPORT_EMAIL_PROTOCOL: ${EMAIL_PROTOCOL}
      GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL: ${WEB_INTERFACE_URL}
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: ${EMAIL_HOSTNAME}
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: ${EMAIL_ENABLED}
      GRAYLOG_TRANSPORT_EMAIL_PORT: ${EMAIL_PORT}
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: ${EMAIL_USE_AUTH}
      GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME: ${EMAIL_AUTH_USERNAME}
      GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD: ${EMAIL_AUTH_PASSWORD}
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      GRAYLOG_TRANSPORT_FROM_EMAIL: ${FROM_EMAIL}
      GRAYLOG_TRANSPORT_SUBJECT_PREFIX: ${SUBJECT_PREFIX}

    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    volumes:
      - "./config/graylog/graylog.conf:/usr/share/graylog/config/graylog.conf"
      - "graylog_data:/usr/share/graylog/data"
    networks:
      - backend
    restart: always
    depends_on:
      opensearch:
        condition: "service_started"
      mongo:
        condition: "service_started"
    ports:
      - 9000:9000/tcp   # Graylog web interface and REST API
      - 1514:1514/tcp   # Syslog
      - 1514:1514/udp   # Syslog
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
