---
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    network_mode: "host"
    ports:
      - 53:53/tcp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ./work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    restart: unless-stopped