version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower 
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=Europe/Malta
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE="0 30 3 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro      

networks:
  proxy:
    external: true  