---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    networks:
      - proxy  
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=http"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.local.example.com`)"
      - "traefik.http.middlewares.heimdall-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.heimdall.middlewares=heimdall-https-redirect"
      - "traefik.http.routers.heimdall-secure.entrypoints=https"
      - "traefik.http.routers.heimdall-secure.rule=Host(`heimdall.local.example.com`)"
      - "traefik.http.routers.heimdall-secure.tls=true"
      - "traefik.http.routers.heimdall-secure.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - 'traefik.http.routers.heimdall-secure.middlewares=authelia@docker'
    restart: unless-stopped

networks:
  proxy:
    external: true