version: "3"

services:
  ampache:
    image: ampache/ampache
    container_name: ampache
    restart: unless-stopped
    networks:
      - proxy 
    volumes:
      - /mnt/music:/media
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.ampache.entrypoints=http"
       - "traefik.http.routers.ampache.rule=Host(`ampache.local.example.com`)"
       - "traefik.http.middlewares.ampache-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.ampache.middlewares=ampache-https-redirect"
       - "traefik.http.routers.ampache-secure.entrypoints=https"
       - "traefik.http.routers.ampache-secure.rule=Host(`ampache.local.example.com`)"
       - "traefik.http.routers.ampache-secure.tls=true"
       - "traefik.http.routers.ampache-secure.service=ampache"
       - "traefik.http.services.ampache.loadbalancer.server.port=8080"
       - "traefik.docker.network=host"
       - 'traefik.http.routers.ampache-secure.middlewares=authelia@docker'

networks:
  proxy:
    external: true 