---
networks:
  backend:
    external: true

volumes:
  config:
    driver: local

services:
  name:
    image:
    user: 1000:1000
    container_name:
    command: ""
    environment:
      - PUID=
      - PGID=
      - TZ=Etc/UTC
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  config: