---
services:
  OpenSpeedTest:
    image: openspeedtest/latest:latest
    container_name: OpenSpeedTest
    command:
     - nginx, -g , daemon off;
    ports:
      - 3200:3000
    restart: unless-stopped