---
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-app
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8080:80
    networks:
      - wordpress-net  
    restart: unless-stopped
    depends_on:
      - wordpress-db

  wordpress-db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    # ports:
    #   - 3306:3306
    networks:
      - wordpress-net   
    restart: unless-stopped

volumes:
  wordpress:
  db:

networks:
  wordpress-net:
    external: true