version: "3.8"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Malta
    volumes:
      - ./appdata:/config
      - ./data:/data
      - local:/local:rw
    ports:
      - 9443:443

volumes:
  local:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.21.20,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/storage0/nextcloud"

networks:
  proxy:
    external: true
