---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./appdata:/config
      - ./data:/data
      - local:/local:rw
    ports:
      - 9443:443
    restart: unless-stopped