---
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    networks:
      - proxy     
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Malta
      # - PASSWORD=PASSWORD
    volumes:
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=Host(`librespeed.local.example.com`)"
      - "traefik.http.middlewares.librespeed-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.librespeed.middlewares=librespeed-https-redirect"
      - "traefik.http.routers.librespeed-secure.entrypoints=https"
      - "traefik.http.routers.librespeed-secure.rule=Host(`librespeed.local.example.com`)"
      - "traefik.http.routers.librespeed-secure.tls=true"
      - "traefik.http.routers.librespeed-secure.service=librespeed"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true