version: "3.8"

services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Malta
      - NZBGET_USER=avalon649 #optional
      - NZBGET_PASS=Jj8zLEXc5MpFLa #optional
    volumes:
      - ./config:/config
      - downloads:/downloads #optional
    ports:
      - 6789:6789

volumes:
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.21.20,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/storage0/plex/downloads"

networks:
  proxy:
    external: true
