---
networks:
  backend:
    external: true

services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Malta
      - NZBGET_USER=username
      - NZBGET_PASS=password
    ports:
      - 6789:6789
    volumes:
      - ./config:/config
      - downloads:/downloads
    restart: unless-stopped
    networks:
      - backend

volumes:
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.21.20,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/storage0/plex/downloads"