---
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: 'Etc/UTC'
      WEBPASSWORD: 'password'
    volumes:
      - ./etcd:/etc/pihole
      - ./dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" only needed if dhcp is active
      - "80:80/tcp"
      - "443:443/tcp"
    env_file:
      - .env      
    restart: unless-stopped