version: "3"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Malta
    volumes:
      - ./appdata:/config
      - ./data:/data
    ports:
      - 9443:443  

  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped  
    networks:
      - proxy  
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=1234567890
      - TZ=Europe/Malta
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=1234567890
    volumes:
      - ./mariadb/config:/config
      
networks:
  proxy:
    external: true