---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
     - 80:80
     - 443:443
    volumes:
      - config:/config
    restart: unless-stopped
    networks:
      - heimdall

volumes:
  config:
    driver: local    

networks:
  heimdall:
    external: true    