---
services:
  dim:
    image: ghcr.io/dusk-labs/dim:dev
    container_name: Dim
    volumes:
      - ./config:/opt/dim/config 
      - ./movies:/mnt/movies
      - ./music:/mnt/music
      - ./series:/mnt/series
    # devices: 
    #   - /dev/dri/renderD128:/dev/dri/renderD128  
    ports:
      - 8000:8000  
    restart: unless-stopped      