---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  username:
    displayname: "username"
    # Password is Authelia
    password: "$argon2id$v=p@55w0rd"
    email: admin@example.com
    groups:
      - admins
      - dev
...