---
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    ports:
       - 80:80
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true